currency_characters = [
    'AED', 'AFN', 'ALL', 'AMD', 'ANG', 'AOA', 'ARS', 'AUD', 'AWG', 'AZN',
    'BAM', 'BBD', 'BDT', 'BGN', 'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BOV',
    'BRL', 'BSD', 'BTN', 'BWP', 'BYN', 'BZD', 'CAD', 'CDF', 'CHE', 'CHF',
    'CHW', 'CLF', 'CLP', 'CNY', 'COP', 'COU', 'CRC', 'CUC', 'CUP', 'CVE',
    'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'ERN', 'ETB', 'EUR', 'FJD',
    'FKP', 'GBP', 'GEL', 'GHS', 'GIP', 'GMD', 'GNF', 'GTQ', 'GYD', 'HKD',
    'HNL', 'HRK', 'HTG', 'HUF', 'IDR', 'ILS', 'INR', 'IQD', 'IRR', 'ISK',
    'JMD', 'JOD', 'JPY', 'KES', 'KGS', 'KHR', 'KMF', 'KPW', 'KRW', 'KWD',
    'KYD', 'KZT', 'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'LYD', 'MAD', 'MDL',
    'MGA', 'MKD', 'MMK', 'MNT', 'MOP', 'MRU', 'MUR', 'MVR', 'MWK', 'MXN',
    'MXV', 'MYR', 'MZN', 'NAD', 'NGN', 'NIO', 'NOK', 'NPR', 'NZD', 'OMR',
    'PAB', 'PEN', 'PGK', 'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD',
    'CNY', 'RUB', 'RWF', 'SAR', 'SBD', 'SCR', 'SDG', 'SEK', 'SGD', 'SHP',
    'SLL', 'SOS', 'SRD', 'SSP', 'STN', 'SVC', 'SYP', 'SZL', 'THB', 'TJS',
    'TMT', 'TND', 'TOP', 'TRY', 'TTD', 'TWD', 'TZS', 'UAH', 'UGX', 'USD',
    'USN', 'UYI', 'UYU', 'UYW', 'UZS', 'VED', 'VES', 'VND', 'VUV', 'WST',
    'XAF', 'XAG', 'XAU', 'XBA', 'XBB', 'XBC', 'XBD', 'XCD', 'XDR', 'XOF',
    'XPD', 'XPF', 'XPT', 'XSU', 'XTS', 'XUA', 'XXX', 'YER', 'ZAR', 'ZMW',
    'ZWL'
]



currency_names = [
    'UAE Dirham', 'Afghani', 'Lek', 'Armenian Dram', 'Netherlands Antillean Guilder', 'Kwanza',
    'Argentine Peso', 'Australian Dollar', 'Aruban Guilder', 'Azerbaijanian Manat',
    'Convertible Mark', 'Barbados Dollar', 'Taka', 'Bulgarian Lev', 'Bahraini Dinar',
    'Burundi Franc', 'Bermudian Dollar', 'Brunei Dollar', 'Boliviano', 'Mvdol',
    'Brazilian Real', 'Bahamian Dollar', 'Ngultrum', 'Pula', 'Belarusian Ruble',
    'Belize Dollar', 'Canadian Dollar', 'Congolese Franc', 'WIR Euro', 'Swiss Franc',
    'WIR Franc', 'Unidad de Fomento', 'Chilean Peso', 'Yuan Renminbi', 'Colombian Peso',
    'Unidad de Valor Real', 'Costa Rican Colon', 'Cuban Convertible Peso', 'Cuban Peso',
    'Cape Verde Escudo', 'Czech Koruna', 'Djibouti Franc', 'Danish Krone',
    'Dominican Peso', 'Algerian Dinar', 'Egyptian Pound', 'Nakfa', 'Ethiopian Birr',
    'Euro', 'Fiji Dollar', 'Falkland Islands Pound', 'Pound Sterling', 'Lari',
    'Ghana Cedi', 'Gibraltar Pound', 'Dalasi', 'Guinea Franc', 'Quetzal',
    'Guyana Dollar', 'Hong Kong Dollar', 'Lempira', 'Croatian Kuna', 'Gourde',
    'Forint', 'Rupiah', 'New Israeli Sheqel', 'Indian Rupee', 'Iraqi Dinar',
    'Iranian Rial', 'Iceland Krona', 'Jamaican Dollar', 'Jordanian Dinar',
    'Yen', 'Kenyan Shilling', 'Som', 'Riel', 'Comorian Franc', 'North Korean Won',
    'Won', 'Kuwaiti Dinar', 'Cayman Islands Dollar', 'Tenge', 'Lao Kip',
    'Lebanese Pound', 'Sri Lanka Rupee', 'Liberian Dollar', 'Loti', 'Libyan Dinar',
    'Moroccan Dirham', 'Moldovan Leu', 'Malagasy Ariary', 'Denar', 'Kyat',
    'Tugrik', 'Pataca', 'Ouguiya', 'Mauritius Rupee', 'Rufiyaa', 'Kwacha',
    'Mexican Peso', 'Mexican Unidad de Inversion (UDI)', 'Malaysian Ringgit',
    'Mozambique Metical', 'Namibia Dollar', 'Naira', 'Cordoba Oro', 'Norwegian Krone',
    'Nepalese Rupee', 'New Zealand Dollar', 'Rial Omani', 'Balboa', 'Sol',
    'Kina', 'Philippine Peso', 'Pakistan Rupee', 'Zloty', 'Guarani', 'Qatari Rial',
    'Romanian Leu', 'Serbian Dinar', 'Yuan Renminbi', 'Russian Ruble', 'Rwanda Franc',
    'Saudi Riyal', 'Solomon Islands Dollar', 'Seychelles Rupee', 'Sudanese Pound',
    'Swedish Krona', 'Singapore Dollar', 'Saint Helena Pound', 'Leone', 'Somali Shilling',
    'Surinam Dollar', 'South Sudanese Pound', 'Dobra', 'El Salvador Colon',
    'Syrian Pound', 'Lilangeni', 'Baht', 'Somoni', 'Turkmenistan New Manat',
    'Tunisian Dinar', 'Pa’anga', 'Turkish Lira', 'Trinidad and Tobago Dollar',
    'New Taiwan Dollar', 'Tanzanian Shilling', 'Hryvnia', 'Uganda Shilling',
    'US Dollar', 'US Dollar (Next day)', 'Uruguay Peso en Unidades Indexadas (UI)',
    'Peso Uruguayo', 'Unidad Previsional', 'Uzbekistan Sum', 'Venezuelan Bolívar',
    'Venezuelan Bolívar Soberano', 'Dong', 'Vatu', 'Tala', 'CFA Franc BEAC',
    'Silver', 'Gold', 'Bond Markets Unit European Composite Unit (EURCO)',
    'Bond Markets Unit European Monetary Unit (E.M.U.-6)', 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
    'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 'East Caribbean Dollar',
    'SDR (Special Drawing Right)', 'CFA Franc BCEAO', 'Palladium', 'CFP Franc',
    'Platinum', 'Sucre', 'Codes specifically reserved for testing purposes',
    'ADB Unit of Account', 'The codes assigned for transactions where no currency is involved',
    'Yemeni Rial', 'Rand', 'Zambian Kwacha', 'Zimbabwe Dollar'
]





currency_data = {
    "INR": {"main": {"en": "Rupees", "hi": "रुपये"}, "sub": {"en": "Paise", "hi": "पैसे"}},
    "KWD": {"main": {"en": "Dinar", "ar": "دينار كويتي"}, "sub": {"en": "Fils", "ar": "فلس"}},
    "USD": {"main": {"en": "Dollars"}, "sub": {"en": "Cents"}},
    "EUR": {"main": {"en": "Euros"}, "sub": {"en": "Cents"}},
    "AED": {"main": {"en": "Dirhams", "ar": "درهم إماراتي"}, "sub": {"en": "Fils", "ar": "فلس"}},
    "SAR": {"main": {"en": "Riyals", "ar": "ريال سعودي"}, "sub": {"en": "Halala", "ar": "هللة"}},
    "QAR": {"main": {"en": "Riyals", "ar": "ريال قطري"}, "sub": {"en": "Dirham", "ar": "درهم"}},
    "OMR": {"main": {"en": "Rial", "ar": "ريال عماني"}, "sub": {"en": "Baisa", "ar": "بيسة"}},
    "BHD": {"main": {"en": "Dinar", "ar": "دينار بحريني"}, "sub": {"en": "Fils", "ar": "فلس"}},
    "JOD": {"main": {"en": "Dinar", "ar": "دينار أردني"}, "sub": {"en": "Piastre", "ar": "قرش"}},
    "EGP": {"main": {"en": "Pound", "ar": "جنيه مصري"}, "sub": {"en": "Piastre", "ar": "قرش"}},
    "GBP": {"main": {"en": "Pounds"}, "sub": {"en": "Pence"}},
    "PKR": {"main": {"en": "Rupees"}, "sub": {"en": "Paisa"}},
    "BDT": {"main": {"en": "Taka"}, "sub": {"en": "Paisa"}},
    "LKR": {"main": {"en": "Rupees"}, "sub": {"en": "Cents"}},
    "NPR": {"main": {"en": "Rupees"}, "sub": {"en": "Paisa"}},
    "MYR": {"main": {"en": "Ringgit"}, "sub": {"en": "Sen"}},
    "IDR": {"main": {"en": "Rupiah"}, "sub": {"en": "Sen"}},
    "THB": {"main": {"en": "Baht"}, "sub": {"en": "Satang"}},
    "VND": {"main": {"en": "Dong"}, "sub": {"en": "Hao"}},
    "CNY": {"main": {"en": "Yuan"}, "sub": {"en": "Fen"}},
    "JPY": {"main": {"en": "Yen"}, "sub": {"en": "Sen"}},
    "KRW": {"main": {"en": "Won"}, "sub": {"en": "Jeon"}},
    "ZAR": {"main": {"en": "Rand"}, "sub": {"en": "Cents"}},
    "AUD": {"main": {"en": "Dollars"}, "sub": {"en": "Cents"}},
    "CAD": {"main": {"en": "Dollars"}, "sub": {"en": "Cents"}},
    "NZD": {"main": {"en": "Dollars"}, "sub": {"en": "Cents"}},
    "CHF": {"main": {"en": "Francs"}, "sub": {"en": "Rappen"}},
    "SEK": {"main": {"en": "Kronor"}, "sub": {"en": "Öre"}},
    "DKK": {"main": {"en": "Krone"}, "sub": {"en": "Øre"}}
}
