# Generated by Django 5.1.2 on 2025-02-13 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
