# Generated by Django 5.1.2 on 2025-03-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeissue',
            name='issue_sign',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
