# Generated by Django 5.1.2 on 2024-12-11 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequetemplate',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chq_pay.banks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chequetemplate',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chq_pay.currencies'),
            preserve_default=False,
        ),
    ]
