# Generated by Django 5.1.2 on 2025-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chqpayuser',
            name='privilege_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
