# Generated by Django 5.1.2 on 2024-12-12 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeissue',
            name='issue_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chq_pay.banks'),
        ),
        migrations.AlterField(
            model_name='chequeissue',
            name='issue_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chq_pay.currencies'),
        ),
    ]
