# Generated by Django 5.1.2 on 2025-03-18 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0002_alter_chequeissue_issue_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='payee_acc_no',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payee',
            name='payee_bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chq_pay.banks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banks',
            name='bank_name_l',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
