# Generated by Django 5.1.2 on 2025-02-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0002_appuser_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='expiry_date',
            field=models.CharField(max_length=50),
        ),
    ]
