# Generated by Django 5.1.2 on 2025-04-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0002_alter_chqpayuser_privilege_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequetemplate',
            name='amount_char_limit',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chequetemplate',
            name='payee_char_limit',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
