# Generated by Django 5.1.2 on 2024-12-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0002_alter_chequeissue_issue_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequeissue',
            name='issue_amount_wrd',
            field=models.CharField(default='One Lakh', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chequeissue',
            name='issue_sign',
            field=models.ImageField(blank=True, null=True, upload_to='Signatures/'),
        ),
    ]
