# Generated by Django 5.1.2 on 2025-03-18 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0003_payee_payee_acc_no_payee_payee_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='payee_acc_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='payee_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chq_pay.banks'),
        ),
    ]
