# Generated by Django 5.1.2 on 2025-04-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0003_chequetemplate_amount_char_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequetemplate',
            name='amount_char_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chequetemplate',
            name='payee_char_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
