# Generated by Django 5.1.2 on 2024-12-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0003_chequeissue_issue_amount_wrd_chequeissue_issue_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_code', models.IntegerField()),
                ('license_key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('cust_id', models.CharField(max_length=200)),
                ('country_id', models.IntegerField()),
                ('country_name', models.CharField(max_length=100)),
                ('allowed_templates', models.IntegerField()),
            ],
        ),
    ]
