# Generated by Django 5.1.2 on 2025-03-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0004_tempdatas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
