# Generated by Django 5.1.2 on 2025-05-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0004_alter_chequetemplate_amount_char_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequetext',
            name='amtnum_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='amtnum_font',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='amtnum_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='amtnum_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='amtwrds_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='amtwrds_font',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='amtwrds_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='amtwrds_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='date_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='date_font',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='date_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='date_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='payee_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='payee_font',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='payee_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='payee_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='sign_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='sign_font',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='sign_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chequetext',
            name='sign_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
