# Generated by Django 5.1.2 on 2025-01-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0004_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeissue',
            name='issue_amount',
            field=models.FloatField(),
        ),
    ]
