# Generated by Django 5.1.2 on 2025-03-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0005_alter_payee_email_alter_payee_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='tel_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
