# Generated by Django 5.1.2 on 2025-05-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0005_chequetext_amtnum_bold_chequetext_amtnum_font_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequetext',
            name='sign_bold',
        ),
        migrations.RemoveField(
            model_name='chequetext',
            name='sign_font',
        ),
        migrations.RemoveField(
            model_name='chequetext',
            name='sign_italic',
        ),
        migrations.RemoveField(
            model_name='chequetext',
            name='sign_size',
        ),
    ]
