# Generated by Django 5.1.2 on 2025-01-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0005_alter_chequeissue_issue_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeissue',
            name='issue_amount',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
    ]
