# Generated by Django 5.1.2 on 2025-03-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0006_alter_banks_address_alter_banks_tel_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_setup',
            name='auth_sign',
            field=models.ImageField(blank=True, null=True, upload_to='company_auth_sign/'),
        ),
    ]
