# Generated by Django 5.1.2 on 2025-01-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0006_alter_chequeissue_issue_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequeissue',
            name='issue_amount_wrd',
        ),
    ]
