# Generated by Django 5.1.2 on 2025-01-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0007_remove_chequeissue_issue_amount_wrd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_setup',
            name='currency_id',
        ),
    ]
