# Generated by Django 5.1.2 on 2025-01-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0008_remove_company_setup_currency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_setup',
            name='is_selected',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
