# Generated by Django 5.1.2 on 2025-01-11 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0009_company_setup_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chq_pay.company_setup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chequeissue',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chq_pay.company_setup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chequetemplate',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chq_pay.company_setup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencies',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chq_pay.company_setup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payee',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chq_pay.company_setup'),
            preserve_default=False,
        ),
    ]
