# Generated by Django 5.1.2 on 2025-01-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0010_banks_company_chequeissue_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chqpayuser',
            name='civil_id',
        ),
        migrations.RemoveField(
            model_name='chqpayuser',
            name='privilege_char',
        ),
        migrations.AddField(
            model_name='chqpayuser',
            name='privilege_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
