# Generated by Django 5.1.2 on 2025-01-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0011_remove_chqpayuser_civil_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banks',
            name='company',
        ),
        migrations.RemoveField(
            model_name='currencies',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payee',
            name='company',
        ),
    ]
