# Generated by Django 5.1.2 on 2025-01-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0012_remove_banks_company_remove_currencies_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_setup',
            name='is_selected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
