# Generated by Django 5.1.2 on 2025-01-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0013_alter_company_setup_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_setup',
            name='is_selected',
            field=models.BooleanField(),
        ),
    ]
