# Generated by Django 5.1.2 on 2025-01-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0014_alter_company_setup_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequeissue',
            name='issue_approvedby',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chequeissue',
            name='issue_is_approved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
