# Generated by Django 5.1.2 on 2025-01-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0016_alter_chequeissue_issue_approvedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeissue',
            name='issue_approvedby',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
