# Generated by Django 5.1.2 on 2025-01-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0017_alter_chequeissue_issue_approvedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeissue',
            name='issue_is_approved',
            field=models.BooleanField(blank=True),
        ),
    ]
