# Generated by Django 5.1.2 on 2025-01-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0018_alter_chequeissue_issue_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeissue',
            name='issue_is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
