# Generated by Django 5.1.2 on 2025-01-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0019_alter_chequeissue_issue_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chequeissue',
            old_name='issue_approvedby',
            new_name='issue_approv_rejectby',
        ),
    ]
