# Generated by Django 5.1.2 on 2025-01-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0020_rename_issue_approvedby_chequeissue_issue_approv_rejectby'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequeissue',
            name='issue_accountnum',
            field=models.IntegerField(default=1234567896666),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chequeissue',
            name='issue_amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
