# Generated by Django 5.1.2 on 2025-01-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_pay', '0021_chequeissue_issue_accountnum_payee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeissue',
            name='issue_amount',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
    ]
